
language: python
python:
  - 2.7
cache: pip

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest
  - pip install codecov

script: py.test --cov=./

after_success: codecov
